services:
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/react_app:/app
    
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      
  docusaurus:
    build:
      context: ../docs
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    profiles:
      - docs